version: 2.1

commands: # a reusable command with parameters
  greeting:
    parameters:
      name:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.name>>"
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - greeting:
          name: "Chris"
workflows:
  my-workflow:
    jobs:
      - my-job
